name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: vuepress-deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: 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
          TARGET_REPO: simonKimathi/knowledgebase
          TARGET_BRANCH: deploy
          BUILD_SCRIPT: yarn && yarn build
          BUILD_DIR: src/.vuepress/dist/